### ISSUE TITLE
Crash when returning to the app

### ISSUE THREAD

**Issue by cristin** [krazykira/VidEffects#9]
Hi, 

First of all, thank you for this library. Is such a helpful one. 
I started playing around with it and I get the following exception when returning to the app. Do you any idea why this is happening? Thank you!

FATAL EXCEPTION: GLThread 19220
                  Process: com.famous.app, PID: 9602
                  Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexo, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
                  java.lang.IllegalStateException
                      at android.media.MediaPlayer._setVideoSurface(Native Method)
                      at android.media.MediaPlayer.setSurface(MediaPlayer.java:753)
                      at com.sherazkhilji.videffect.view.VideoSurfaceView$VideoRender.onSurfaceCreated(VideoSurfaceView.java:257)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by cristin** [comment]
Sorry, scratch that, I just found the problem. I was releasing the mediaplayer in onPause.
